<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Configuration.proto

namespace Aria2_remote;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aria2_remote.Configuration</code>
 */
class Configuration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool error_status = 1;</code>
     */
    private $error_status = false;
    /**
     * Generated from protobuf field <code>bool system_status = 2;</code>
     */
    private $system_status = false;

    public function __construct() {
        \GPBMetadata\Proto\Configuration::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool error_status = 1;</code>
     * @return bool
     */
    public function getErrorStatus()
    {
        return $this->error_status;
    }

    /**
     * Generated from protobuf field <code>bool error_status = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setErrorStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->error_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool system_status = 2;</code>
     * @return bool
     */
    public function getSystemStatus()
    {
        return $this->system_status;
    }

    /**
     * Generated from protobuf field <code>bool system_status = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSystemStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->system_status = $var;

        return $this;
    }

}

