<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Configuration.proto

namespace GPBMetadata\Proto;

class Configuration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6f0a1970726f746f2f436f6e66696775726174696f6e2e70726f746f12" .
            "0c61726961325f72656d6f7465223c0a0d436f6e66696775726174696f6e" .
            "12140a0c6572726f725f73746174757318012001280812150a0d73797374" .
            "656d5f737461747573180220012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

